### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by tumuyan** [HaujetZhao/ShortcutMapper_Chinese#2]
这个项目非常有用，试用后觉得可以从这几个方面再优化一下：
1. 增加配色选择（包含页面背景和键盘配色）当前页面是白色的，至少需要增加一个黑色的配色作为夜间模式 （我甚至想让键盘兼容这个项目   https://github.com/ijprest/keyboard-layout-editor）
2. 页面尺寸自适应。当屏幕宽度不低于一定值时，尽量让页面不需要滚动
3. 目前汉字搜索需要至少两个字才出结果，应该改为1个就出结果。考虑到上一个问题，建议同步修改为搜索在页面最下方，搜索结果以fixed并底部对齐的布局方式展示。
4. 打包为可执行文件，用快捷键全屏召唤，快捷键隐藏。好处是操作更方便，更符合实际使用的操作逻辑。这个功能可以通过打包为electron来实现（实际上我昨晚已经百度了下打包方式做了打包，并且打包后避免了浏览器权限的问题）你觉得有没有必要？或者有没有什么更好的想法？众所周知element的开销比较大。如果这是可以接受的方法，你看是自己打包还是我提pr？
5. 快捷键收藏功能。用列表展示用户精选的按键组合，提醒自己的需要熟记的重要按键。免除了搜索和看图的时间。
6. 不同软件间相同功能的快捷键对照。按下一组快捷键，在页面下方提示和其他软件中，和这组快捷键相同名字的按键组合是什么

**Comment by HaujetZhao** [comment]
在考研，现在没空做。

关于外观，我也觉得不够好，例如：

- 按键横向只能显示4个汉字，字体已经最小，不能再小
- 按键太老气

剩下的，我能力还不行，也没空深究。考完研也有好多东西要学（我连 HTML、js 都还没学），结构、外观、功能上的调整短时间还做不了。

我目前能做的，就是 readme 里面那样，通过表格和脚本的形式增加、修改快捷键。

electron 不太好。你可以看到我在项目中，已经有了一个 python 脚本，就叫 `启动.py`，它会在当前文件夹提供网络服务到指定端口，运行后就是这样：

```
已在地址 :: 的 8000 端口上启用了 HTTP 服务
请访问这个链接： http://[::]:8000/
```

不再担心浏览器权限问题了。体积也小巧。

也可以挂载到 github pages、gitee pages，只要访问过后，也是可以离线访问的。

**Comment by tumuyan** [comment]
好的，了解了。
我们的思路还是有些差异（毕竟你在小众也看过我的想法，我打算完成一个不同软件快捷键归一化+快捷键提示的软件，所以用单独窗口的程序是很有必要的），现在已经先按自己的思路把这个项目做成了electron版本的软件  https://github.com/tumuyan/ShortcutMapper_Chinese 
 。
网页的部分我也略懂一点，后边会力所能及的做些完善并给你这边提pr。

**Comment by tumuyan** [comment]
补充新的功能需求：
1. 目前只显示了键盘的快捷键，需要补充鼠标操作，以及鼠标和键盘的组合
2. 针对快捷键进行分组（譬如ide的build debug 逐行 逐过程 跳出 停止 就是典型的一组功能，而文件内查找 目录内查找 查找下一个 查找上一个 替换，这是另一组功能。在页面底部可以展示当前软件有哪些快捷键分组，然后点击分组可以看到相关联的快捷键（这样更有学习效率）
